name: Build & Deploy
run-name: ${{ github.actor }} is building our project 🚀
on: [push]
jobs:
  Build-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        working-directory: labs/docker/vehicle/backend
        run: |
          ls ${{ github.workspace }}
          ./build.sh
